# Generated by Django 3.2.9 on 2022-05-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information_source', '0002_alter_feesstructure_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='year',
        ),
    ]
