# Generated by Django 3.2.9 on 2022-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default='doe', max_length=50, verbose_name='Middle Name'),
            preserve_default=False,
        ),
    ]
