# Generated by Django 3.2.9 on 2022-05-05 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20220504_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 9, 38, 9, 514867, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='images/default_user_avatar.png', upload_to='images/', verbose_name='Picture'),
        ),
    ]
