# Generated by Django 3.2.9 on 2022-05-05 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20220505_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 5, 5, 16, 0, 58, 595896, tzinfo=utc)),
        ),
    ]
