# Generated by Django 3.2.9 on 2022-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0002_alter_financialaccount_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=7),
        ),
    ]
