# Generated by Django 3.2.9 on 2022-05-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0004_financialaccount_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialaccount',
            old_name='balance',
            new_name='arrears',
        ),
    ]
