# Generated by Django 3.2.9 on 2022-05-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_account', '0005_rename_balance_financialaccount_arrears'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ['-date_of_payment']},
        ),
    ]
