# Generated by Django 3.2.9 on 2022-05-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220512_1216'),
        ('financial_account', '0007_currentbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
