# Generated by Django 3.2.9 on 2022-05-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='seconday_contact_phone_number',
            new_name='secondary_contact_phone_number',
        ),
    ]
