# Generated by Django 3.2.9 on 2022-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('admission', models.IntegerField()),
                ('diary_and_report_book', models.IntegerField()),
                ('interview_fee_lower_classes', models.IntegerField()),
                ('interview_fee_upper_classes', models.IntegerField()),
                ('play_group', models.IntegerField()),
                ('pre_primary', models.IntegerField()),
                ('grade_1_to_3', models.IntegerField()),
                ('primary_std_1_to_4', models.IntegerField()),
                ('hot_lunch', models.IntegerField()),
                ('transport', models.IntegerField()),
            ],
        ),
    ]
