# Generated by Django 3.2.9 on 2022-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesstructure',
            name='pre_primary2',
            field=models.IntegerField(default=5600),
            preserve_default=False,
        ),
    ]
