# Generated by Django 3.2.9 on 2022-05-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_feesstructure_pre_primary2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesstructure',
            old_name='pre_primary',
            new_name='pre_primary1',
        ),
        migrations.RenameField(
            model_name='feesstructure',
            old_name='primary_std_1_to_4',
            new_name='primary_std_4_to_8',
        ),
    ]
