# Generated by Django 3.2.9 on 2022-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20220505_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term_1_start_date', models.DateField()),
                ('term_1_mid_term_break_start', models.DateField()),
                ('term_1_mid_term_break_end', models.DateField()),
                ('term_1_end_date', models.DateField()),
                ('term_2_start_date', models.DateField()),
                ('term_2_mid_term_break_start', models.DateField()),
                ('term_2_mid_term_break_end', models.DateField()),
                ('term_2_end_date', models.DateField()),
                ('term_3_mid_term_break_start', models.DateField()),
                ('term_3_mid_term_break_end', models.DateField()),
                ('term_3_start_date', models.DateField()),
            ],
        ),
    ]
