# Generated by Django 3.2.9 on 2022-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_academiccalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='term_3_end_date',
            field=models.DateField(default='2020-1-1'),
            preserve_default=False,
        ),
    ]
