# Generated by Django 3.2.9 on 2022-05-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20220507_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='kcpe_end_date',
            field=models.DateField(default='2022-1-1'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='kcpe_start_date',
            field=models.DateField(default='2022-1-1'),
        ),
    ]
