# Generated by Django 3.2.9 on 2022-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20220507_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='kcpe_end_date',
            field=models.DateTimeField(default='2022-1-1'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='kcpe_start_date',
            field=models.DateTimeField(default='2022-1-1'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_1_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_1_mid_term_break_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_1_mid_term_break_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_1_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_2_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_2_mid_term_break_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_2_mid_term_break_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_2_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_3_end_date',
            field=models.DateTimeField(default='2022-1-1'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_3_mid_term_break_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_3_mid_term_break_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='term_3_start_date',
            field=models.DateTimeField(default='2022-1-1'),
        ),
    ]
