# Generated by Django 3.2.9 on 2022-05-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20220509_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesstructure',
            name='interview_fee',
        ),
    ]
